[package]
name = "deploy_script"
version = "0.1.0"
edition = "2025_12"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[[target.starknet-contract]]
name = "deploy_script_target"

[executable]

[dependencies]
cairo_execute = "2.16.0"
sncast_std = "0.57.0"
starknet = ">=2.16.0"
